# Generated by Django 5.1.5 on 2025-03-10 09:58

import dctapp.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('d_name', models.CharField(max_length=255)),
                ('phn_no', models.CharField(max_length=10, unique=True)),
                ('d_email', models.EmailField(max_length=255)),
                ('d_ward_no', models.CharField(max_length=200)),
                ('d_available_days', models.JSONField(default=list)),
                ('d_start_time', models.TimeField()),
                ('d_end_time', models.TimeField()),
                ('d_education_info', models.TextField(blank=True, max_length=200, null=True)),
                ('d_certifications', models.TextField(blank=True, max_length=200, null=True)),
                ('d_department', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='dctapp.speciality')),
            ],
        ),
    ]
