# Generated by Django 5.1.5 on 2025-03-10 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dctapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='d_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dctapp.speciality'),
        ),
    ]
