# Generated by Django 5.1.5 on 2025-03-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dctapp', '0002_alter_doctoravailability_d_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='phn_no',
            new_name='d_phn_no',
        ),
    ]
